
name: â™»ï¸ Sync Labels

on:
  push:
    paths:
      - .github/labels.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  labels:
    name: â™»ï¸ Sync labels
    runs-on: ubuntu-20.04
    permissions:
      issues: write
      contents: read
    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4

      - name: ğŸš€ Run Label Sync
        uses: srealmoreno/label-sync-action@v2
        with:
          config-file: https://raw.githubusercontent.com/Flutter-Journey/.github/main/.github/labels.yml

      - name: ğŸš€ Run Label Sync (Local)
        if: ${{ hashFiles('.github/labels.yml') }}
        uses: srealmoreno/label-sync-action@v2
        with:
          config-file: .github/labels.yml

